AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - vendor/bundle/**/*
    - db/schema.rb

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/GuardClause:
  Enabled: false
