name: Ruby CI
on: [push, pull_request]
jobs:
  test:
    runs-on: macos-latest

    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tableIncomAndExpeditureWithERB_test
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
      - name: Install dependencies
        run: bundle install
      - name: Setup test database
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        run: |
          bundle exec rails db:create db:schema:load --trace
      - name: Run tests
        run: rails test test/units
