name: Ruby CI
on: [push, pull_request]
jobs:
  test:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
      - name: Install dependencies
        run: bundle install
      - name: Setup test database
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: vladislav
        run: |
          bundle exec rails db:create db:schema:load --trace
      - name: Run tests
        run: rails test test/units
